### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by bmullan91** [nearform/graphql-hooks-memcache#6]
Reuse https://github.com/nearform/graphql-hooks/blob/master/CONTRIBUTING.md

**Comment by jackdclark** [comment]
Closing as this repo has moved to [graphql-hooks](https://github.com/nearform/graphql-hooks) and this is covered by https://github.com/nearform/graphql-hooks/blob/master/CONTRIBUTING.md
